<?php
/* @var ThaisCmky\CustomerFilters\Block\ProductSearch $block */
?>
<div id="product-search" data-bind="scope:'product-search'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
        }
    }
    </script>
    <script>
        window.storeCurrencySymbol = '<?php /* @noEscape */ echo $block->getCurrencySymbol(); ?>';
        window.storeCurrency = '<?php /* @noEscape */ echo $block->getCurrency(); ?>';
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
        })
    </script>
</div>

<!--
    <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
-->
